/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Asset { 
    /**
     * Automatically generated ID
     */
    id?: number;
    /**
     * Asset name
     */
    name?: string;
    /**
     * Asset description
     */
    description?: string;
    /**
     * ID of AssetGroup that Asset belongs to
     */
    assetGroupId: number;
}

