/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (Schema options: { exclude: [ \'id\', \'userId\' ] })
 */
export interface AssetGroupExcludingIdUserId { 
    /**
     * AssetGroup name
     */
    name?: string;
    /**
     * AssetGroup description
     */
    description?: string;
}

