/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (Schema options: { exclude: [ \'id\', \'authToken\', \'config\', \'userId\' ] })
 */
export interface DataLoggerExcludingIdAuthTokenConfigUserId { 
    /**
     * Datalogger description
     */
    description?: string;
    /**
     * Method used by DataLogger to send data to the system. At present only FTP implemented
     */
    connectionType: string;
    /**
     * Format of the files uploaded to the system DataLogger. At present system supports CSV and XML formats
     */
    fileFormat: string;
    /**
     * Username of system FTP account, where the DataLogger sends the data (if applicable)
     */
    username?: string;
    /**
     * Password of system FTP account, where the DataLogger sends the data (if applicable)
     */
    passwd?: string;
    /**
     * Flag for selecting if DataLogger is to be initiated automatically from preexisting configuration
     */
    autoInit: boolean;
    /**
     * Flag for selecting if DataLogger sends compressed files
     */
    dataCompressed: boolean;
}

