/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DataFloat { 
    /**
     * Automatically generated ID
     */
    id?: number;
    /**
     * Recording period - seconds
     */
    period: number;
    /**
     * Recorded measurement
     */
    measurement: number;
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * ID of Channel that DataFloat belongs to
     */
    channelId: number;
}

