/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Device { 
    /**
     * Automatically generated ID
     */
    id?: number;
    /**
     * Device description
     */
    description?: string;
    /**
     * Device serial number
     */
    serialNo: string;
    /**
     * ID of DataLogger that Device belongs to
     */
    dataLoggerId: number;
    /**
     * ID of DeviceType associated with Device
     */
    deviceTypeId: number;
}

