/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (Schema options: { exclude: [ \'id\', \'resolved\', \'timestamp\', \'resolutionTimestamp\' ] })
 */
export interface EventExcludingIdResolvedTimestampResolutionTimestamp { 
    /**
     * ID of Asset associated with Event
     */
    assetId: number;
    /**
     * ID of EventRule triggered
     */
    eventRuleId: number;
    /**
     * Event severity - Can be  LOW / MEDIUM / HIGH
     */
    severity: string;
    /**
     * Event description
     */
    description?: string;
}

