/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventRuleSubscription { 
    /**
     * Automatically generated ID
     */
    id?: number;
    /**
     * EventRule execution period - seconds
     */
    executionPeriod: number;
    /**
     * Last execution timestamp
     */
    lastExecTimestamp?: string;
    /**
     * ID of Asset subscribed to EventRule
     */
    assetId: number;
    /**
     * ID of associated EventRule
     */
    eventRuleId: number;
    /**
     * Is set to true when EventRule has been activated
     */
    ruleActivated: boolean;
}

