/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventRule { 
    /**
     * Automatically generated ID
     */
    id?: number;
    /**
     * Rule description
     */
    description?: string;
    /**
     * Rule scope
     */
    scope: string;
    /**
     * Rule action
     */
    action: string;
    /**
     * Rule action parameters
     */
    actionParameters?: string;
}

