/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse2002Basic } from './inlineResponse2002Basic';
import { InlineResponse2002BasicTemperature } from './inlineResponse2002BasicTemperature';
import { InlineResponse2002Wind } from './inlineResponse2002Wind';


export interface InlineResponse2002 { 
    Basic?: InlineResponse2002Basic;
    Wind?: InlineResponse2002Wind;
    SolarRadiation?: InlineResponse2002BasicTemperature;
}

