/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse2002BasicTemperature } from './inlineResponse2002BasicTemperature';


export interface InlineResponse2002Basic { 
    Temperature?: InlineResponse2002BasicTemperature;
    Humidity?: InlineResponse2002BasicTemperature;
    Pressure?: InlineResponse2002BasicTemperature;
}

