/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse2001StringList } from './inlineResponse2001StringList';
import { InlineResponse2001UnresolvedIssueList } from './inlineResponse2001UnresolvedIssueList';


export interface InlineResponse2001InverterList { 
    InverterID?: number;
    InverterSN?: string;
    StringList?: Array<InlineResponse2001StringList>;
    UnresolvedIssueList?: Array<InlineResponse2001UnresolvedIssueList>;
}

