/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse2001LastMeasurementDCVoltage } from './inlineResponse2001LastMeasurementDCVoltage';


export interface InlineResponse2001LastMeasurement { 
    DC_Voltage?: InlineResponse2001LastMeasurementDCVoltage;
    DC_Current?: InlineResponse2001LastMeasurementDCVoltage;
}

