/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse2001LastMeasurement } from './inlineResponse2001LastMeasurement';
import { InlineResponse2001UnresolvedIssueList } from './inlineResponse2001UnresolvedIssueList';


export interface InlineResponse2001StringList { 
    String_Identifier?: string;
    LastMeasurement?: InlineResponse2001LastMeasurement;
    UnresolvedIssueList?: Array<InlineResponse2001UnresolvedIssueList>;
}

