/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.2
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (Schema options: { title: \'LoginCredentials\', exclude: [ \'id\', \'email\', \'isVirtual\', \'roles\' ] })
 */
export interface LoginCredentials { 
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    passwd: string;
}

