/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.2
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (Schema options: { title: \'NewUser\', exclude: [ \'id\', \'username\', \'isVirtual\', \'roles\' ] })
 */
export interface NewUser { 
    /**
     * Password
     */
    passwd: string;
    /**
     * Email
     */
    email: string;
}

