/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestDataLoggerSetupCsv2DataHeaderLocationKeysNumber } from './requestDataLoggerSetupCsv2DataHeaderLocationKeysNumber';
import { RequestDataLoggerSetupCsv2DataHeaderLocationKeysStrArray } from './requestDataLoggerSetupCsv2DataHeaderLocationKeysStrArray';
import { RequestDataLoggerSetupCsv2DataHeaderLocationKeysArray } from './requestDataLoggerSetupCsv2DataHeaderLocationKeysArray';


/**
 * (Schema options: { exclude: [ \'fileFormat\' ] })
 */
export interface RequestDataLoggerSetupCsv2DataHeaderLocation { 
    /**
     * First column of header
     */
    firstItemCol: number;
    /**
     * Relevant row location of next item
     */
    nextItemIteration: number;
    model: RequestDataLoggerSetupCsv2DataHeaderLocationKeysArray;
    serialNo: RequestDataLoggerSetupCsv2DataHeaderLocationKeysArray;
    channelName: RequestDataLoggerSetupCsv2DataHeaderLocationKeysStrArray;
    channelUnit: RequestDataLoggerSetupCsv2DataHeaderLocationKeysStrArray;
    period: RequestDataLoggerSetupCsv2DataHeaderLocationKeysNumber;
}

