/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestDataLoggerSetupCsv2LocationSpec } from './requestDataLoggerSetupCsv2LocationSpec';


/**
 * (Schema options: { exclude: [ \'fileFormat\' ] })
 */
export interface RequestDataLoggerSetupCsv2TimeData { 
    /**
     * Column containing time data
     */
    column: number;
    /**
     * Row containing first value of time data in the CSV file
     */
    firstItemRow: number;
    /**
     * Relevant row location of next item
     */
    nextItemIteration: number;
    timezone: RequestDataLoggerSetupCsv2LocationSpec;
    format: RequestDataLoggerSetupCsv2LocationSpec;
}

