/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestEventRuleScope } from './requestEventRuleScope';


export interface RequestEventCreateRule { 
    /**
     * Rule description
     */
    description: string;
    scope: Array<RequestEventRuleScope>;
    /**
     * Rule action
     */
    action: string;
    /**
     * Action Parameters
     */
    actionParameters: object;
}

