/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataFloat } from './dataFloat';
import { DataText } from './dataText';
import { ChannelType } from './channelType';


export interface ResponseDeviceChannelData { 
    channelType: ChannelType;
    dataFloat?: Array<DataFloat>;
    dataText?: Array<DataText>;
}

