/**
 * Atman IoT
 * Atman IoT Server
 *
 * The version of the OpenAPI document: 0.2.3
 * Contact: k.khoury@k-ren.gr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    /**
     * Automatically generated ID
     */
    id?: number;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    passwd: string;
    /**
     * Email
     */
    email: string;
    roles?: Array<string>;
    /**
     * Automatically assigned flag to select if User is virtual or not
     */
    isVirtual: boolean;
}

