/**
 * project
 * OneDrive
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: DataWithRelations, schemaOptions: { includeRelations: true })
 */
export interface DataWithRelations { 
    id?: number;
    bar1: number;
    bar2: number;
    bar3: number;
    bar4: number;
    upperIND1: boolean;
    upperIND2: boolean;
    upperIND3: boolean;
    upperIND4: boolean;
    hours: number;
    timer: boolean;
    lowIND11: boolean;
    lowIND12: boolean;
    lowIND13: boolean;
    lowIND14: boolean;
    lowIND21: boolean;
    lowIND22: boolean;
    lowIND23: boolean;
    lowIND24: boolean;
    lowIND31: boolean;
    lowIND32: boolean;
    lowIND33: boolean;
    lowIND34: boolean;
    lowIND41: boolean;
    lowIND42: boolean;
    lowIND43: boolean;
    lowIND44: boolean;
    timestamp: string;
    flagIsOk: boolean;
}

