/**
 * project
 * OneDrive
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnyType } from './anyType';


export interface RawData { 
    id?: number;
    data: Array<AnyType>;
}

